### ISSUE TITLE
scrape_config's `module` parameter does not seem to be passed to the prometheus

### ISSUE THREAD

**Issue by mkalcok** [canonical/blackbox-exporter-k8s-operator#11]
### Bug Description

`module` parameter does not seem to be properly passed to the Prometheus when scrape job is created.

### To Reproduce

1. \<deploy cos\>
2. juju deploy --channel=edge blackbox-exporter-k8s
3. juju config blackbox-exporter-k8s config_file='@./config.yaml'
4. juju relate blackbox-exporter-k8s prometheus
5. juju config blackbox-exporter-k8s probes_file='@./probes.yaml'

config.yaml:
```
modules:
  https_2xx:
    http:
      fail_if_not_ssl: true
      follow_redirects: true
      method: GET
      tls_config:
        insecure_skip_verify: false
      valid_http_versions:
      - HTTP/1.1
      - HTTP/2.0
      valid_status_codes: []
    prober: http
    timeout: 5s
````

probes.yaml:
```
scrape_configs:
  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [https_2xx]
    static_configs:
      - targets:
        - https://example.org
```

### Environment

juju snap: 3.2.3
juju controller: 3.2.2
blackbox-exporter-k8s char: rev. 2
prometheus char: rev. 103

### Relevant log output

```shell
Scrape job configuration as seen in Prometheus:

- job_name: juju_cos-external-targets_8a913a02_blackbox-exporter-k8s_prometheus_scrape_blackbox
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __param_target
    replacement: $1
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: probe_target
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: blackbox-exporter-k8s-0.blackbox-exporter-k8s-endpoints.cos-external-targets.svc.cluster.local:9115
    action: replace
  - source_labels: [juju_model, juju_model_uuid, juju_application]
    separator: _
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  static_configs:
  - targets:
    - https://example.org
    labels:
      juju_application: blackbox-exporter-k8s
      juju_charm: blackbox-exporter-k8s
      juju_model: cos-external-targets
      juju_model_uuid: 8a913a02-10e0-4acf-8582-fe1d07e9faf9
```

### Additional context

As can be seen in the Prometheus' job configuration, `module` parameter was not configured. Correct configuration should contain
```yaml
  params:
    module:
    - https_2xx
```

**Comment by lucabello** [comment]
Cannot reproduce with the latest charm revision; the scrape job now correctly contains a new module `https_2xx_new` I used to try to reproduce the issue:

```yaml
params:
    module:
    - https_2xx_new
```

Closing!
