### ISSUE TITLE
Target port changed from port 9115 to port 80 between rev 17 and rev 22

### ISSUE THREAD

**Issue by ggouzi** [canonical/blackbox-exporter-k8s-operator#54]
### Bug Description

Blackbox-exporter targets are configured with port 80 instead of port 9115. Making them unreachable.
Blackbox-exporter targets used to be correctly configured to use port 9115 before (rev 17)

### To Reproduce

- Deploy cos-lite with blackbox-exporter latest/stable (rev 22)

```
juju deploy -m cos cos-lite --trust --overlay ./config/cos/cos-overlay.yaml
```

- Check Proemtheus targets in the UI. They are reachable over port 80 and down/unreachable

- Downgrade to rev 17 of BB-exporter
```
juju refresh blackbox-exporter --revision=17
```

- Check Proemtheus targets in the UI. They are reachable over port 9115 and up/running

### Environment

Juju 3.6.2
BB-exporter latest/stable rev 22

### Relevant log output

Please refer to screenshots attached. One using rev 17, the other one using rev22

Rev 22
![Image](https://github.com/user-attachments/assets/95d42347-6425-499c-8a02-51b7a57fb29c)

Rev 17
![Image](https://github.com/user-attachments/assets/2627f0df-d89a-49cb-bea6-aaf6b1f9194d)

### Additional context

cos-overlay.yaml

```
bundle: kubernetes
applications:
  blackbox-exporter:
    charm: blackbox-exporter-k8s
    channel: latest/stable
    trust: true
    scale: 1
    # revision: 17
    options:
      config_file: |
        modules:
          tcp_connect:
            prober: tcp
            tcp:
              ip_protocol_fallback: false
              preferred_ip_protocol: ip4
              tls: true
              tls_config:
                insecure_skip_verify: true
            timeout: 15s
      probes_file: |
        scrape_configs:
          - job_name: 'blackbox-exporter-kafka-certificates-monitoring'
            metrics_path: /probe
            params:
              module: [tcp_connect]
            static_configs:
              - targets:
                - kafhdev-XXX:9093
                - kafhdev-XXX:9093
                - kafhdev-XXX:9093
            relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - target_label: __address__
              replacement: blackbox-exporter-0.blackbox-exporter-endpoints.cos.svc.cluster.local:9115

relations:
- ["prometheus:metrics-endpoint", "blackbox-exporter:self-metrics-endpoint"]
- ["grafana:grafana-dashboard", "blackbox-exporter:grafana-dashboard"]
```

_No response_
